module.exports = {
    MAX_NUMBER_OF_CHILDREN: 3,
    MAX_NUMBER_OF_ADULTS: 3,
    MAX_NUMBER_OF_INFINTS: 3,
    MAX_NUMBER_OF_ROOMS_PER_BOOKING: 3,
    MAX_NUMBER_OF_CHILDREN_AND_ADULTS_PER_BOOKING: 7,
    MIN_NUMBER_OF_ADULTS_PER_ROOM: 1,
};